### ISSUE TITLE
More detailed description of the application/environments (dev, test, acc, prod)

### ISSUE THREAD

**Issue by frankcorneliusmartin** [IKNL/vantage6-docs#3]

**Comment by arturomoncadatorres** [comment]
Added description for server and node based on https://en.wikipedia.org/wiki/Development,_testing,_acceptance_and_production.

- Server
https://docs.vantage6.ai/v/1.0.0/usage/running-the-server/server-configuration#configuration-file-structure

- Node
https://docs.vantage6.ai/v/1.0.0/usage/running-the-node/configuration#configuration-file-structure
