### ISSUE TITLE
Explain parameters of node

### ISSUE THREAD

**Issue by frankcorneliusmartin** [IKNL/vantage6-docs#4]
Explain the parameters used to create a server / node (`vnode new` and `vserver new`)

**Comment by arturomoncadatorres** [comment]
In the docs drafts, I created a couple of tables for the description of the parameters. There were a few where I wasn't 100% sure. @frankcorneliusmartin could you please take a look and complete them?

**Comment by frankcorneliusmartin** [comment]
I think this section applies to the configuration file in general and not to the wizard specific. Also the defaults depend on your use-case (e.g. testing, deploying etc.)

**Comment by frankcorneliusmartin** [comment]
I made a start with the server parameters:
https://docs.vantage6.ai/usage/running-the-server/server-configuration#parameter-description

**Comment by frankcorneliusmartin** [comment]
**Node:**
https://docs.vantage6.ai/usage/running-the-node/configuration#parameter-description

**Server:**
https://docs.vantage6.ai/usage/running-the-server/server-configuration#parameter-description
