### ISSUE TITLE
Update images 

### ISSUE THREAD

**Issue by frankcorneliusmartin** [IKNL/vantage6-docs#5]
Still see:
- distributed learning
- joey
- ppdli

in the images. Should update them! 😄

**Comment by intGRen** [comment]
Hey, can I get a link for this

**Comment by frankcorneliusmartin** [comment]
You mean these?:
https://docs.vantage6.ai/usage/running-the-server/server-configuration
https://docs.vantage6.ai/usage/running-the-server/shell
https://docs.vantage6.ai/usage/running-the-node/configuration

**Comment by intGRen** [comment]
Updated the images to the what the latest version looks like

**Comment by frankcorneliusmartin** [comment]
I think something went wrong, @intGRen could you check this?:
https://docs.vantage6.ai/usage/running-the-server/shell
