### ISSUE TITLE
Extend What to install section

### ISSUE THREAD

**Issue by frankcorneliusmartin** [IKNL/vantage6-docs#6]
- client instructions are missing
- maybe explain the different components a bit more, and usecases when to install what!

**Comment by frankcorneliusmartin** [comment]
@arturomoncadatorres I updated this page. Could you check it and see if it makes more sense now?

**Comment by arturomoncadatorres** [comment]
Ahhh nice! Yes, much better. Should we wait until finishing the "Development of vantage6" and "Development of algorithms for vantage6" before closing this issue?

**Comment by frankcorneliusmartin** [comment]
Yes, I think we need a seperate page for those. Or maybe use dev-docs.vantage6.ai for this. So that why I left them open for now.

**Comment by frankcorneliusmartin** [comment]
The section "Algorithm development" will be added in a later release.
